/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
// Parameter defaults.
const float defaultGain = 0.75f;

//==============================================================================
AttenuatorAudioProcessor::AttenuatorAudioProcessor()
{
    gain = defaultGain;
}

AttenuatorAudioProcessor::~AttenuatorAudioProcessor()
{
}

//==============================================================================
const String AttenuatorAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int AttenuatorAudioProcessor::getNumParameters()
{
    return totalNumParams;
}

float AttenuatorAudioProcessor::getParameter (int index)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!
    switch (index)
    {
        case gainParam:     return gain;
        default:            return 0.0f;
    }
}

void AttenuatorAudioProcessor::setParameter (int index, float newValue)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!
    switch (index)
    {
        case gainParam:     gain = newValue;  break;
        default:            break;
    }
}

const String AttenuatorAudioProcessor::getParameterName (int index)
{
    switch (index)
    {
        case gainParam:     return "gain";
        default:            break;
    }

    return String::empty;
}

const String AttenuatorAudioProcessor::getParameterText (int index)
{
    return String (getParameter (index), 2);
}

const String AttenuatorAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String AttenuatorAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool AttenuatorAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool AttenuatorAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool AttenuatorAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool AttenuatorAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool AttenuatorAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double AttenuatorAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int AttenuatorAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int AttenuatorAudioProcessor::getCurrentProgram()
{
    return 0;
}

void AttenuatorAudioProcessor::setCurrentProgram (int index)
{
}

const String AttenuatorAudioProcessor::getProgramName (int index)
{
    return String();
}

void AttenuatorAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void AttenuatorAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void AttenuatorAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void AttenuatorAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
        buffer.applyGain(channel, 0, buffer.getNumSamples(), gain);
    }
}

//==============================================================================
bool AttenuatorAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* AttenuatorAudioProcessor::createEditor()
{
    return new AttenuatorAudioProcessorEditor (*this);
}

//==============================================================================
void AttenuatorAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // Here's an example of how you can use XML to make it easy and more robust:

    // Create an outer XML element..
    XmlElement xml ("MYPLUGINSETTINGS");

    // add some attributes to it..
    xml.setAttribute ("gain", gain);

    // then use this helper function to stuff it into the binary blob and return it..
    copyXmlToBinary (xml, destData);
}

void AttenuatorAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.

    // This getXmlFromBinary() helper function retrieves our XML from the binary blob..
    ScopedPointer<XmlElement> xmlState (getXmlFromBinary (data, sizeInBytes));

    if (xmlState != nullptr)
    {
        // make sure that it's actually our type of XML object..
        if (xmlState->hasTagName ("MYPLUGINSETTINGS"))
        {
            // ok, now pull out our parameters..
            gain  = (float) xmlState->getDoubleAttribute ("gain", gain);
        }
    }
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new AttenuatorAudioProcessor();
}
